#!/usr/bin/env bash

set -e

if brew --prefix openssl &>/dev/null; then
  OPENSSL_ROOT=$(brew --prefix openssl)
  export PYTHON_CONFIGURE_OPTS="CPPFLAGS=-I"$OPENSSL_ROOT"/include LDFLAGS=-L"$OPENSSL_ROOT"/lib"
fi
PYTHON_BUILD_DEFINITIONS=`autovenv builddefspath` autovenv-python-build "$1" "`autovenv pyversionspath`/$1"
